apiVersion: v1
kind: ConfigMap
metadata:
  name: lacr-config
  namespace: lacr-loan
data:
  SERVER_PORT: "8012"
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 50MB
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 50MB
  APP_SECURITY_ALLOWED_ORIGIN_PATTERNS: https://lacr-ops.example.com
