apiVersion: v1
kind: ConfigMap
metadata:
  name: lacr-config
  namespace: lacr-loan
data:
  SERVER_PORT: "8012"
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_SHOW_SQL: "false"
  LACR_OUTBOX_PUBLISHER_MODE: kafka
  LACR_OUTBOX_KAFKA_CONSUMER_ENABLED: "true"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka.platform.svc.cluster.local:9092
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 50MB
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 50MB
  APP_SECURITY_ALLOWED_ORIGIN_PATTERNS: https://lacr-ops.example.com
