apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lacr-secret-sync
  namespace: lacr-loan
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: lacr-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: lacr/prod
        property: datasource-url
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: lacr/prod
        property: datasource-username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: lacr/prod
        property: datasource-password
    - secretKey: SPRING_DATA_REDIS_HOST
      remoteRef:
        key: lacr/prod
        property: redis-host
    - secretKey: SPRING_DATA_REDIS_PORT
      remoteRef:
        key: lacr/prod
        property: redis-port
    - secretKey: SPRING_DATA_MONGODB_URI
      remoteRef:
        key: lacr/prod
        property: mongodb-uri
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: lacr/prod
        property: mysql-root-password
    - secretKey: MYSQL_APP_PASSWORD
      remoteRef:
        key: lacr/prod
        property: mysql-app-password
    - secretKey: APP_SECURITY_CLOSUREOPS_PASSWORD
      remoteRef:
        key: lacr/prod
        property: closureops-password
    - secretKey: APP_SECURITY_RECONLEAD_PASSWORD
      remoteRef:
        key: lacr/prod
        property: reconlead-password
    - secretKey: APP_SECURITY_AUDITOR_PASSWORD
      remoteRef:
        key: lacr/prod
        property: auditor-password
    - secretKey: APP_SECURITY_OPSADMIN_PASSWORD
      remoteRef:
        key: lacr/prod
        property: opsadmin-password
