lacr.outbox.publisher.mode=${LACR_OUTBOX_PUBLISHER_MODE:kafka}
lacr.outbox.kafka.consumer.enabled=${LACR_OUTBOX_KAFKA_CONSUMER_ENABLED:true}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
